using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace SailScores.ImportExport.Sailwave.Tests.Utilities
{
    class LhycFile
    {

        public static StreamReader GetStream()
        {
            byte[] byteArray = Encoding.ASCII.GetBytes(_fileContents);
            var stream = new MemoryStream(byteArray);

            return new StreamReader(stream);
        }


        private static string _fileContents =
                "\"serallowfixedflights\",\"0\",\"\",\"\"\r\n\"sersocial\",\"0\",\"\",\"\"\r\n" +
                "\"serversion\",\"2.19.8\",\"\",\"\"\r\n\"serisaflink\",\"http://www.sailing.org/bio.asp?ID=*\",\"\",\"\"\r\n" +
                "\"serisafpub\",\"1\",\"\",\"\"\r\n\"serflagslink\",\"http://www.sailwave.com/flags/small/*.jpg\",\"\",\"\"\r\n" +
                "\"serflagspub\",\"0\",\"\",\"\"\r\n\"serflagstext\",\"0\",\"\",\"\"\r\n\"serhidediscards\",\"0\",\"\",\"\"\r\n" +
                "\"sernodiscardformat\",\"0\",\"\",\"\"\r\n\"serhidefields\",\"0\",\"\",\"\"\r\n\"sersep\",\"0\",\"\",\"\"\r\n" +
                "\"serseprow\",\"0\",\"\",\"\"\r\n\"serpubpbreak\",\"0\",\"\",\"\"\r\n\"serpubfirstn\",\"0\",\"\",\"\"\r\n" +
                "\"serdatespec\",\"m/d/y\",\"\",\"\"\r\n\"serpubincludecodes\",\"0\",\"\",\"\"\r\n" +
                "\"serpubincludecontents\",\"0\",\"\",\"\"\r\n\"serincludelaps\",\"0\",\"\",\"\"\r\n" +
                "\"serincludestarttimes\",\"0\",\"\",\"\"\r\n\"serincludefinishtimes\",\"0\",\"\",\"\"\r\n" +
                "\"serincludecorrected\",\"0\",\"\",\"\"\r\n\"serincludedncs\",\"0\",\"\",\"\"\r\n" +
                "\"serincludespeed\",\"0\",\"\",\"\"\r\n\"serincludeewin\",\"0\",\"\",\"\"\r\n" +
                "\"serincluderwin\",\"0\",\"\",\"\"\r\n\"serpubincluderaces\",\"2\",\"\",\"\"\r\n" +
                "\"serpubincluderaces2\",\"2\",\"\",\"\"\r\n\"serpubincludenotes\",\"0\",\"\",\"\"\r\n" +
                "\"serpubincludeseries\",\"0\",\"\",\"\"\r\n\"serpubincludeprizes\",\"0\",\"\",\"\"\r\n" +
                "\"serpubincludedates\",\"0\",\"\",\"\"\r\n\"serpubincludetimes\",\"0\",\"\",\"\"\r\n" +
                "\"serpubstartcols\",\"0\",\"\",\"\"\r\n\"serhidepropbar\",\"0\",\"\",\"\"\r\n" +
                "\"serpropbarwidth\",\"120\",\"\",\"\"\r\n\"serpropbartree\",\"0\",\"\",\"\"\r\n" +
                "\"serdoscripts\",\"0\",\"\",\"\"\r\n\"serhideexcluded\",\"0\",\"\",\"\"\r\n" +
                "\"serhideunsailed\",\"0\",\"\",\"\"\r\n\"sereventeid\",\"sws0792616079669444\",\"\",\"\"\r\n" +
                "\"serpoponofftitle\",\"\",\"\",\"\"\r\n\"serpoponoffcolumns\",\"Race ,   Sign On   ,   Sign Off\",\"\",\"\"\r\n" +
                "\"serentrytitle\",\"Race Declaration List,Competitor List\",\"\",\"\"\r\n" +
                "\"serentrycolumns\",\"Race 1, Race 2, Race 3\",\"\",\"\"\r\n" +
                "\"serdecalttitle\",\"Declaration of Alternative Penalties\",\"\",\"\"\r\n" +
                "\"serdecaltcolumns\",\"Date   ,Race   ,Class/SailNo   ,Description of Incident,Alternative Penalty (e.g. 720),Initials\",\"\",\"\"\r\n" +
                "\"serdecaltrows\",\"25\",\"\",\"\"\r\n\"sernoticetitle\",\"Competitor Notice\",\"\",\"\"\r\n" +
                "\"seronofftitle\",\"Sign On/Off Declaration\",\"\",\"\"\r\n" +
                "\"seronoffcolumns\",\"Date    ,Race    ,Class/SailNo    ,Sign On        ,Sign Off\",\"\",\"\"\r\n" +
                "\"seronoffrows\",\"25\",\"\",\"\"\r\n\"serdecrettitle\",\"Declaration of Retirements\",\"\",\"\"\r\n" +
                "\"serdecretcolumns\",\"Date   ,Race   ,Class/SailNo   ,Ret Code,Initials\",\"\",\"\"\r\n" +
                "\"serdecretrows\",\"25\",\"\",\"\"\r\n\"serpubincluderacetables\",\"0\",\"\",\"\"\r\n" +
                "\"serpubflightrace\",\"1\",\"\",\"\"\r\n\"serscoringhandle\",\"5\",\"\",\"\"\r\n" +
                "\"sersortcol\",\"12\",\"\",\"\"\r\n\"sersortcol2\",\"12\",\"\",\"\"\r\n" +
                "\"sersortdir\",\"-1\",\"\",\"\"\r\n\"sersortdir2\",\"-1\",\"\",\"\"\r\n" +
                "\"serlistface\",\"Arial\",\"\",\"\"\r\n\"serlistsize\",\"10\",\"\",\"\"\r\n" +
                "\"serlistcolour\",\"0\",\"\",\"\"\r\n\"serelapsedview\",\"1\",\"\",\"\"\r\n" +
                "\"scrfollowchamp\",\"0\",\"5\",\"\"\r\n\"scrfollowmedal\",\"0\",\"5\",\"\"\r\n" +
                "\"scrfollowcodes\",\"0\",\"5\",\"\"\r\n\"scrfollowratingsystem\",\"0\",\"5\",\"\"\r\n" +
                "\"scrfollowratingmode\",\"0\",\"5\",\"\"\r\n\"scrfollowpointssystem\",\"0\",\"5\",\"\"\r\n" +
                "\"scrfollowcoefficients\",\"0\",\"5\",\"\"\r\n\"scrfollowcustomexprs\",\"0\",\"5\",\"\"\r\n" +
                "\"scrfollowseriesties\",\"0\",\"5\",\"\"\r\n\"scrfollowoverallpoints\",\"0\",\"5\",\"\"\r\n" +
                "\"scrfollowdiscards\",\"0\",\"5\",\"\"\r\n\"scrfollowraceties\",\"0\",\"5\",\"\"\r\n" +
                "\"scrfollowflights\",\"0\",\"5\",\"\"\r\n\"scrfollowpointsplaces\",\"0\",\"5\",\"\"\r\n" +
                "\"scrfollowqualification\",\"0\",\"5\",\"\"\r\n\"scrhotkey\",\"0\",\"5\",\"\"\r\n" +
                "\"scrname\",\"Appendix A\",\"5\",\"\"\r\n\"scrparent\",\"0\",\"5\",\"\"\r\n" +
                "\"scrtie0\",\"No\",\"5\",\"\"\r\n\"scrtie1\",\"Yes\",\"5\",\"\"\r\n" +
                "\"scrincludediscards\",\"No\",\"5\",\"\"\r\n\"scrtie2\",\"Yes\",\"5\",\"\"\r\n" +
                "\"scrtie2back\",\"No\",\"5\",\"\"\r\n\"scrtie2starts\",\"No\",\"5\",\"\"\r\n" +
                "\"scrtiefinals\",\"No\",\"5\",\"\"\r\n\"scrraceties\",\"Averaged\",\"5\",\"\"\r\n" +
                "\"scrpointsplaces\",\"1\",\"5\",\"\"\r\n\"scrpointsaccumulation\",\"Sum\",\"5\",\"\"\r\n" +
                "\"scrpointssystem\",\"Low point\",\"5\",\"\"\r\n\"scrratingsystem\",\"None\",\"5\",\"\"\r\n" +
                "\"scrratingvalue\",\"No\",\"5\",\"\"\r\n\"scrwindstrengths\",\"0-1,2-3,4,5-9\",\"5\",\"\"\r\n" +
                "\"scrupdateratings\",\"No\",\"5\",\"\"\r\n\"scrbackcalcpercent\",\"0\",\"5\",\"\"\r\n" +
                "\"scrdiscardlist\",\"0,0,1,1,1,1,1,1,2\",\"5\",\"\"\r\n\"scrflights\",\"No\",\"5\",\"\"\r\n" +
                "\"scrfinals\",\"No\",\"5\",\"\"\r\n\"scrfinalsstickyq\",\"No\",\"5\",\"\"\r\n" +
                "\"scrfinalsfirst\",\"9\",\"5\",\"\"\r\n\"scrlowweight\",\"Yes\",\"5\",\"\"\r\n" +
                "\"scrmedal\",\"No\",\"5\",\"\"\r\n\"scrmedalrace\",\"2\",\"5\",\"\"\r\n" +
                "\"scrmedalyesnotdiscardable\",\"Yes\",\"5\",\"\"\r\n\"scrmedalyesmultiply\",\"Yes\",\"5\",\"\"\r\n" +
                "\"scrmedalyestie\",\"Yes\",\"5\",\"\"\r\n\"scrmedalnonotdiscardable\",\"Yes\",\"5\",\"\"\r\n" +
                "\"scrmedalnomultiply\",\"Yes\",\"5\",\"\"\r\n\"scrmedalnotie\",\"Yes\",\"5\",\"\"\r\n" +
                "\"scrmedalmax\",\"10\",\"5\",\"\"\r\n" +
                "\"scrcode\",\"BFD|Score like|DNF|Yes|Yes||spare|spare|spare|spare|spare|No|No|No|5||Black flag disqualification under rule 30.3\",\"\",\"\"\r\n" +
                "\"scrcode\",\"DGM|Score like|DSQ|No|Yes||spare|spare|spare|spare|spare|Yes|Yes|No|5||Disqualification not excludable under rule 69.1(b)(2)\",\"\",\"\"\r\n" +
                "\"scrcode\",\"DNC|Boats in series +|1|Yes|No||spare|spare|spare|spare|spare|No|No|No|5||Did not come to the starting area\",\"\",\"\"\r\n" +
                "\"scrcode\",\"DNE|Score like|DSQ|No|Yes||spare|spare|spare|spare|spare|Yes|Yes|No|5||Disqualification (other then DGM) not excludable under rule 88.3(b)\",\"\",\"\"\r\n" +
                "\"scrcode\",\"DNF|Boats in series +|1|Yes|Yes||spare|spare|spare|spare|spare|Yes|No|No|5||Started but did not finish\",\"\",\"\"\r\n\"scrcode\",\"DNS|Score like|DNF|Yes|Yes||spare|spare|spare|spare|spare|No|No|No|5||Came to the start area but did not start\",\"\",\"\"\r\n" +
                "\"scrcode\",\"DPI1|Fixed penalty|1|Yes|Yes||spare|spare|spare|spare|spare|Yes|Yes|Yes|5||1 point discretionary penalty\",\"\",\"\"\r\n\"scrcode\",\"DSQ|Score like|DNF|Yes|Yes||spare|spare|spare|spare|spare|Yes|Yes|No|5||Disqualification\",\"\",\"\"\r\n\"scrcode\",\"OCS|Score like|DNF|Yes|Yes||spare|spare|spare|spare|spare|No|No|No|5||On course side at start or broke rule 30.1\",\"\",\"\"\r\n\"scrcode\",\"OOD|Average (all)||Yes|No||spare|spare|spare|spare|spare|Yes|Yes|No|5||Race officer duty points scored as RDGa\",\"\",\"\"\r\n\"scrcode\",\"RDG|Set points by hand||Yes|Yes||spare|spare|spare|spare|spare|Yes|Yes|Yes|5||Redress - points set by protest hearing\",\"\",\"\"\r\n" +
                "\"scrcode\",\"RDGa|Average (all)||Yes|Yes||spare|spare|spare|spare|spare|Yes|Yes|Yes|5||Redress - average points for all races except the race in question\",\"\",\"\"\r\n" +
                "\"scrcode\",\"RDGb|Average (before)||Yes|Yes||spare|spare|spare|spare|spare|Yes|Yes|Yes|5||Redress - average points for all races preceeding the race in question\",\"\",\"\"\r\n\"scrcode\",\"RET|Score like|DNF|Yes|Yes||spare|spare|spare|spare|spare|Yes|No|No|5||Retired\",\"\",\"\"\r\n\"scrcode\",\"SCP|Percentage penalty|20|Yes|Yes||spare|spare|spare|spare|spare|Yes|Yes|Yes|5||Scoring penalty under rule 44.3\",\"\",\"\"\r\n\"scrcode\",\"ZFP|Percentage penalty|20|Yes|Yes||spare|spare|spare|spare|spare|Yes|Yes|Yes|5||20% penalty under rule 30.2\",\"\",\"\"\r\n" +
                "\"ui\",\"1|0|0|0|0|0|0|0|0|0|0|0|0|0|0\",\"\",\"\"\r\n\"comptally\",\"1\",\"3\",\"\"\r\n\"compexclude\",\"0\",\"3\",\"\"\r\n\"compalias\",\"0\",\"3\",\"\"\r\n\"compmedicalflag\",\"0\",\"3\",\"\"\r\n\"comphelmname\",\"Helm 1\",\"3\",\"\"\r\n\"comphigh\",\"0\",\"3\",\"\"\r\n\"comptally\",\"2\",\"4\",\"\"\r\n\"compexclude\",\"0\",\"4\",\"\"\r\n\"compalias\",\"0\",\"4\",\"\"\r\n\"compmedicalflag\",\"0\",\"4\",\"\"\r\n" +
                "\"comphelmname\",\"Helm 2\",\"4\",\"\"\r\n\"comphigh\",\"0\",\"4\",\"\"\r\n\"racerank\",\"1\",\"\",\"1\"\r\n\"racesailed\",\"1\",\"\",\"1\"\r\n\"racename\",\"Race A\",\"\",\"1\"\r\n\"racestart\",\"||Place|Start 1|||0||0|0||||1\",\"\",\"1\"\r\n\"racerank\",\"2\",\"\",\"2\"\r\n\"racesailed\",\"1\",\"\",\"2\"\r\n\"racename\",\"Race B\",\"\",\"2\"\r\n\"racestart\",\"||Place|Start 1|||0||0|0||||1\",\"\",\"2\"\r\n\"rdisc\",\"0\",\"3\",\"1\"\r\n\"rlps\",\"0\",\"3\",\"1\"\r\n\"rrecpos\",\"1\",\"3\",\"1\"\r\n\"rrestyp\",\"1\",\"3\",\"1\"\r\n\"srat\",\"0\",\"3\",\"1\"\r\n\"rrset\",\"0\",\"3\",\"1\"\r\n\"rdisc\",\"0\",\"3\",\"2\"\r\n\"rlps\",\"0\",\"3\",\"2\"\r\n\"rrecpos\",\"2\",\"3\",\"2\"\r\n\"rrestyp\",\"1\",\"3\",\"2\"\r\n\"srat\",\"0\",\"3\",\"2\"\r\n" +
                "\"rrset\",\"0\",\"3\",\"2\"\r\n\"rdisc\",\"0\",\"4\",\"1\"\r\n\"rlps\",\"0\",\"4\",\"1\"\r\n\"rrecpos\",\"2\",\"4\",\"1\"\r\n\"rrestyp\",\"1\",\"4\",\"1\"\r\n\"srat\",\"0\",\"4\",\"1\"\r\n\"rrset\",\"0\",\"4\",\"1\"\r\n\"rdisc\",\"0\",\"4\",\"2\"\r\n\"rlps\",\"0\",\"4\",\"2\"\r\n\"rrecpos\",\"1\",\"4\",\"2\"\r\n\"rrestyp\",\"1\",\"4\",\"2\"\r\n\"srat\",\"0\",\"4\",\"2\"\r\n\"rrset\",\"0\",\"4\",\"2\"\r\n\"column\",\"1|AltSailNo|15|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Boat|12|Yes|Yes|40||\",\"\",\"\"\r\n\"column\",\"1|BowNumber|7|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|CarriedFwd|207|No|No|20||\",\"\",\"\"\r\n\"column\",\"1|Class|13|Yes|Yes|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|Club|16|Yes|Yes|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|CrewAddress|46|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|CrewAgeGroup|39|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|CrewEmail|40|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|CrewId|38|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|CrewMemberNo|43|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|CrewName|18|Yes|Yes|40||\",\"\",\"\"\r\n\"column\",\"1|CrewNotes|47|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|CrewPhone|44|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|CrewPhoto|45|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|CrewSex|42|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|CrewWebsite|41|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Division|9|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Exclude|2|Yes|No|10|BLANK|\",\"\",\"\"\r\n\"column\",\"1|Fee|198|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|Fleet|8|Yes|Yes|40||\",\"\",\"\"\r\n\"column\",\"1|HelmAddress|36|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|HelmAgeGroup|29|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|HelmEmail|30|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|HelmId|28|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|HelmMemberNo|33|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|HelmName|17|Yes|Yes|40||\",\"\",\"\"\r\n\"column\",\"1|HelmNotes|37|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|HelmPhone|34|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|HelmPhoto|35|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|HelmSex|32|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|HelmWebsite|31|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Medical|5|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MedicalFlag|1|No|No|10|BLANK|\",\"\",\"\"\r\n\"column\",\"1|Nat|23|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Nett|210|Yes|Yes|40||\",\"\",\"\"\r\n\"column\",\"1|NewRating|20|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Notes|211|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Paid|199|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Penalties|208|No|No|20||\",\"\",\"\"\r\n\"column\",\"1|PrivateNotes|212|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Rank|4|Yes|Yes|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|Rating|19|Yes|Yes|40||\",\"\",\"\"\r\n\"column\",\"1|SailNo|14|Yes|Yes|40||\",\"\",\"\"\r\n\"column\",\"1|Status|196|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|Tally|6|Yes|No|40||\",\"\",\"\"\r\n\"column\",\"1|Total|209|Yes|Yes|40||\",\"\",\"\"\r\n\"column\",\"2||206|Yes|Yes|15||\",\"\",\"\"\r\n\"column\",\"3||1000|Yes|No|40|BLANK|\",\"\",\"\"\r\n\"column\",\"1|Alias|3|Yes|No|10|BLANK|\",\"\",\"\"\r\n\"column\",\"1|Flight|10|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Seeding|11|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|WindRats|21|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Formula|22|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Platform|24|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Rig|25|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Sailmaker|26|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Foils|27|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|SkipperName|48|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|SkipperId|49|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|SkipperAgeGroup|50|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|SkipperEmail|51|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|SkipperWebsite|52|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|SkipperSex|53|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|SkipperMemberNo|54|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|SkipperPhone|55|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|SkipperPhoto|56|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|SkipperAddress|57|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|SkipperNotes|58|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|TacticianName|59|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|TacticianId|60|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|TacticianAgeGroup|61|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|TacticianEmail|62|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|TacticianWebsite|63|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|TacticianSex|64|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|TacticianMemberNo|65|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|TacticianPhone|66|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|TacticianPhoto|67|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|TacticianAddress|68|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|TacticianNotes|69|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|NavigatorName|70|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|NavigatorId|71|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|NavigatorAgeGroup|72|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|NavigatorEmail|73|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|NavigatorWebsite|74|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|NavigatorSex|75|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|NavigatorMemberNo|76|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|NavigatorPhone|77|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|NavigatorPhoto|78|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|NavigatorAddress|79|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|NavigatorNotes|80|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|BowmanName|81|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|BowmanId|82|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|BowmanAgeGroup|83|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|BowmanEmail|84|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|BowmanWebsite|85|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|BowmanSex|86|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|BowmanMemberNo|87|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|BowmanPhone|88|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|BowmanPhoto|89|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|BowmanAddress|90|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|BowmanNotes|91|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MastName|92|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MastId|93|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MastAgeGroup|94|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MastEmail|95|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|MastWebsite|96|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MastSex|97|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MastMemberNo|98|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MastPhone|99|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MastPhoto|100|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MastAddress|101|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MastNotes|102|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PitName|103|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PitId|104|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PitAgeGroup|105|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PitEmail|106|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PitWebsite|107|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PitSex|108|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|PitMemberNo|109|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PitPhone|110|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PitPhoto|111|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PitAddress|112|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PitNotes|113|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MaintrimName|114|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MaintrimId|115|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MaintrimAgeGroup|116|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MaintrimEmail|117|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MaintrimWebsite|118|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MaintrimSex|119|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MaintrimMemberNo|120|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MaintrimPhone|121|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|MaintrimPhoto|122|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MaintrimAddress|123|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|MaintrimNotes|124|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PorttrimName|125|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PorttrimId|126|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PorttrimAgeGroup|127|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PorttrimEmail|128|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PorttrimWebsite|129|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PorttrimSex|130|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PorttrimMemberNo|131|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PorttrimPhone|132|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PorttrimPhoto|133|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PorttrimAddress|134|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|PorttrimNotes|135|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|StartrimName|136|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StartrimId|137|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StartrimAgeGroup|138|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StartrimEmail|139|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StartrimWebsite|140|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StartrimSex|141|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StartrimMemberNo|142|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StartrimPhone|143|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StartrimPhoto|144|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StartrimAddress|145|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StartrimNotes|146|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PortgrindName|147|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PortgrindId|148|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|PortgrindAgeGroup|149|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PortgrindEmail|150|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PortgrindWebsite|151|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PortgrindSex|152|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PortgrindMemberNo|153|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PortgrindPhone|154|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PortgrindPhoto|155|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PortgrindAddress|156|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|PortgrindNotes|157|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StargrindName|158|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StargrindId|159|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|StargrindAgeGroup|160|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StargrindEmail|161|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StargrindWebsite|162|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StargrindSex|163|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StargrindMemberNo|164|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StargrindPhone|165|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StargrindPhoto|166|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StargrindAddress|167|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|StargrindNotes|168|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|OwnerName|169|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|OwnerId|170|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|OwnerAgeGroup|171|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|OwnerEmail|172|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|OwnerWebsite|173|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|OwnerSex|174|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|OwnerMemberNo|175|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|OwnerPhone|176|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|OwnerPhoto|177|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|OwnerAddress|178|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|OwnerNotes|179|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|GuestName|180|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|GuestId|181|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|GuestAgeGroup|182|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|GuestEmail|183|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|GuestWebsite|184|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|GuestSex|185|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|GuestMemberNo|186|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|GuestPhone|187|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|GuestPhoto|188|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|GuestAddress|189|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|GuestNotes|190|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|District|191|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|Squad|192|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Area|193|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Region|194|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Group|195|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Medalist|197|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|Sponsor|200|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|SponsorWebsite|201|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|SponsorEmail|202|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|Team|203|No|No|40||\",\"\",\"\"\r\n\"column\",\"1|TeamWebsite|204|No|No|40||\",\"\",\"\"\r\n" +
                "\"column\",\"1|TeamEmail|205|No|No|40||\",\"\",\"\"\r\n";
    }
}
